version: '3.9'
services:
  web:
    build: ./main_site
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./main_site:/django_template
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin_django_template
      - POSTGRES_PASSWORD=hello_django_template
      - POSTGRES_DB=dev_django_template
volumes:
  postgres_data:
